colors:
  primary_color: '#eee'
  secondary_color: '#006cbf'
  accent_color: '#f7be00'
font_embed:
  font_embed_url: https://fonts.googleapis.com/css?family=Nunito&display=swap
  font_family_name: "'Nunito', sans-serif"
heading_settings:
  heading_1_font_size: 2.5rem
  heading_1_font_weight: 700
  heading_2_font_size: 2rem
  heading_2_font_weight: 400
paragraph_settings:
  paragraph_font_size: 1.2rem
  paragraph_font_weight: 300
